server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: nickz
    password: password
    url: jdbc:postgresql://localhost:5433/customer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
