server:
  port: 9090

spring:
  application:
    name: productApi
  datasource:
    username: nickz
    password: password
    url: jdbc:postgresql://localhost:5433/product
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml